BEGIN;

DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "user_roles" CASCADE;
DROP TABLE IF EXISTS "products" CASCADE;
DROP TABLE IF EXISTS "categories" CASCADE;
DROP TABLE IF EXISTS "customers" CASCADE;
DROP TABLE IF EXISTS "orders" CASCADE;
DROP TABLE IF EXISTS "order_items" CASCADE;
DROP TABLE IF EXISTS "payments" CASCADE;
DROP TABLE IF EXISTS "inventory_logs" CASCADE;

DROP SEQUENCE IF EXISTS seq_user_id;
DROP SEQUENCE IF EXISTS seq_product_id;
DROP SEQUENCE IF EXISTS req_customer_id;
DROP SEQUENCE IF EXISTS req_order_id;

DROP TYPE IF EXISTS "enum_order_status";
DROP TYPE IF EXISTS "enum_payment_method";

COMMIT;