BEGIN;

TRUNCATE TABLE "users" CASCADE;
TRUNCATE TABLE "user_roles" CASCADE;
TRUNCATE TABLE "products" CASCADE;
TRUNCATE TABLE "categories" CASCADE;
TRUNCATE TABLE "customers" CASCADE;
TRUNCATE TABLE "orders" CASCADE;
TRUNCATE TABLE "order_items" CASCADE;
TRUNCATE TABLE "payments" CASCADE;
TRUNCATE TABLE "inventory_logs" CASCADE;
TRUNCATE TABLE "oauth" CASCADE;

COMMIT;